version: "3.9"

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: jsk-admin
    ports:
      - "${ADMIN_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: jsk-client
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
